# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beanstalk < Formula
  desc "Terminal-native implementation of the Beans task-file format"
  homepage "https://github.com/kpb/beanstalk"
  version "0.5.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kpb/beanstalk/releases/download/v0.5.0/beanstalk_0.5.0_darwin_amd64.tar.gz"
      sha256 "f15a1d5a9dd8919a532a11ec1b923c9b39092a8066b00f577d9550470d220ce7"

      define_method(:install) do
        bin.install "beanstalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kpb/beanstalk/releases/download/v0.5.0/beanstalk_0.5.0_darwin_arm64.tar.gz"
      sha256 "9ebfae321114d3a1b68fcd02ffacf3cbec827d5c468c082050cc78aeede6d3c2"

      define_method(:install) do
        bin.install "beanstalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpb/beanstalk/releases/download/v0.5.0/beanstalk_0.5.0_linux_amd64.tar.gz"
      sha256 "bd45695688ac1514937731ada694cfbf9a0e7295b9eb0a8d85e225e6ffefbeca"
      define_method(:install) do
        bin.install "beanstalk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpb/beanstalk/releases/download/v0.5.0/beanstalk_0.5.0_linux_arm64.tar.gz"
      sha256 "a2a96a7c23a77287e207de67416e002de19e4882d8d67bfe35279b8a1e1565ae"
      define_method(:install) do
        bin.install "beanstalk"
      end
    end
  end
end
